:time_estimate: 5

= Lab: Install MicroShift from RPM Packages

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Install MicroShift in a RHEL VM that is not connected to the Internet.

WARNING: Work In Progress

== Before you Begin

You need a _test machine_ with RHEL and unrestricted `sudo`, where you will install MicroShift.

You also need a _package server machine_ already configured to serve DNF repositories for the RHEL BaseOS, RHEL AppStream, Fast Data Path for RHEL 9, and Red Hat OpenShift Container Platform. Make sure that your _package server machine_ machine was configured and verified by following the instructions from the xref:ch1-microshift:s3-prepare-lab.adoc[first lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM as the user `student` with password `student`, and you start SSH sessions from `workstation` VM to the `serverb` VM, which is your _test machine_, using the same user. If not, please adapt the instructions to your test environment.

You will perform most steps in this lab on your _test machine_.

== Instructions

// Where to host the mirror-pull-registry and other files? Have them available at $HOME in serverb? Force learners to download it from GitHub or from the classroom/materials server?

1. Log in on your _test machine_ and verify that it has access to the required DNF package repositories.

.. Check that the required package repositories from RHEL and OpenShift are available.
+
If you were connected to the Internet [ or using Red Hat Satellite? ] and had registered your _test machine_ with a valid Red Hat subscription, you would see something similar to:
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf repolist*
Updating Subscription Management repositories.
repo id                                                         repo name
fast-datapath-for-rhel-9-x86_64-rpms                            Fast Datapath for RHEL 9 x86_64 (RPMs)
rhel-9-for-x86_64-appstream-rpms                                Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
rhel-9-for-x86_64-baseos-rpms                                   Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
rhocp-4.17-for-rhel-9-x86_64-rpms                               Red Hat OpenShift Container Platform 4.17 for RHEL 9 x86_64 (RPMs)
--
+
IMPORTANT: Please, do _not_ register any VM on your virtual labs. Please conserve the limited Internet bandwidth which is shared by all learners using ROLE.
+
On the classroom environment, you will find configuration files which point to the _package server machine_ and the names of its DNF repositories match the names of Red Hat DNF repositories.
+
[source,subs="verbatim,quotes"]
--
$ *ls /etc/yum.repos.d*
fdp.repo  ocp4.repo  redhat.repo  rhel_94.repo
$ *cat /etc/yum.repos.d/ocp4.repo*
include::1@samples:yum:example$ocp4.repo[lines=1..3]
...
--

.. As an additional sanity check, search from packages from the OpenShift and RHEL Fast Data Path repositories.
+
[source,subs="verbatim,quotes"]
--
$ *dnf search microshift*
...
microshift.x86_64 : MicroShift service
microshift-greenboot.noarch : Greenboot components for MicroShift
...
$ *dnf search ovn24.09-central*
...
ovn24.09-central.x86_64 : Open Virtual Network support
--

2. Verify that your _test machine_ can access a mirror container image registry that is pre-populared with the container images required by MicroShift.

.. Download a pull secret with enables access to the MicroShift container images.
+
In a system connected to the internet, you would get a pull secret from your Red Hat account from the Red Hat Hybrid Cloud Console.
+
IMPORTANT: Please, do _not_ use your pull secret with VMs on your virtual labs. Please stick to the scenario of an air-gapped deployment of MicroShift, assuming that an IT Operations team already configured all local network infrastructure required for deploying Red Hat Device Edge.
+
For the classroom environment, the pull secret for the mirror registry is available from https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/mirror-pull-secret[GitHub]
+
Check that the pull registry contains credentials for `registry.lab.example.com`.
+
[source,subs="verbatim,quotes"]
--
$ *cat mirror-pull-registry*
include::1@samples:microshift:example$mirror-pull-secret[]
--

.. Add the CA key of the mirror registry to the set of trusted CAs. The public CA key is availabe from the _web server machine_, which in the classroom environment is `servera`, in the `http://servera.lab.example.com/quay-rootCA.pem` URL.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp quay-rootCA.pem /etc/pki/ca-trust/source/anchors*
$ *sudo update-ca-trust*
--

.. As a sanity check, use the pull secret to inspect container images on the mirror registry. It should worth with TLS validation enabled, which is the default for all container tools.
+
[source,subs="verbatim,quotes"]
--
$ *skopeo inspect --authfile mirror-pull-secret '{{.RepoTags}}' docker://registry.lab.example.com:8443/ubi9/ubi*
[latest]
--
+
NOTE: The command above should work with your actual Red Hat pull secret if you change the registry part of the contaimer image name to `redhat.registry.io`, but displaying a long list of tags.

4. Verify that your _test machine_ is configured to support the installation of MicroShift.

.. First of all, MicroShift expects that SELinux is enabled, in enforcing mode, and that Firewalld is enabled. Please to not disable any of them, you there's no need!
+
[source,subs="verbatim,quotes"]
--
$ *getenforce*
Enforcing
$ *systemctl is-enabled firewalld*
enabled
$ *sudo firewall-cmd --list-all*
[sudo] password for student: 
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources: 
  services: cockpit dhcpv6-client pulseaudio ssh
  ports: 8888/tcp
  protocols: 
  forward: no
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules:
--
+
Enable more services and trusted zones or interfaces as you need. Later in this course we'll show wthat to add to enable remote access to MicroShift and Kubernetes applications on it.

.. Check that you have some GB of free disk space on whatever filesystem holds `/var/lib/containers` so you can store container images and ephemeral storage layers from CRI-O containers.
+
In the classroom environment, it is on the root partition of your _test machine_.
+
[source,subs="verbatim,quotes"]
--
$ *df -h /var/lib/containers*
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   10G  7.1G  2.9G  71% /
--

.. Finally, check that you have a volume group named `rhel` with a few GB of unallocated space, so you can create Persistent Volumes (PVs) for your Kubernetes applications.
+
[source,subs="verbatim,quotes"]
--
$ *sudo vgs*
  VG   #PV #LV #SN Attr   VSize   VFree 
  rhel   1   1   0 wz--n- <19.02g <9.02g
--

5. Install the MicroShift packages.
+
You need only one package called `microshift` but pay attention to its dependency list. You will see packages that provide CRI-O and other components of OpenShift, and also packages from Open Virtual Networking (OVN).
+
NOTE: If your system prompts about importing GPG keys, answer "Y".
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install microshift*
[GRAB PACKAGE LIST]
--
+
WARNING: Do not try to start MicroShift yet!

6. Configure MicroShift to use your mirror registry.

.. Download a CRI-O registry configuration, from https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/999-microshift-mirror.conf[GitHub], that redirects contaimer images from Red Hat Registries and Quay.io to the 
mirror registry.
+
[source,subs="verbatim,quotes"]
--
$ *head -n 5 999-microshift-mirror.conf*
include::1@samples:microshift:example$999-microshift-mirror.conf[lines=1..5]
...
--

.. Copy the registry configuration to the container tools registries configuration directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp 999-microshift-mirror.conf /etc/containers/registries.conf.d/999-microshift-mirror.conf*
--

.. Download a CRI-O image policy, from https://raw.githubusercontent.com/RedHatQuickCourses/rhde-build-samples/refs/heads/main/microshift/containers-policy.json.nosigs[GitHub], that allows running any container image, from anywhere, without checking image sigantures.
+
[source,subs="verbatim,quotes"]
--
$ *cat containers-policy.json.nosigs*
include::1@samples:microshift:example$containers-policy.json.nosigs[]
--
+
WARNING: If you skip that step, some Red Hat add-on operator images will fail to run from the mirror registry.

.. Copy the image policy to the container tools registries configuration directory.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp containers-policy.json.nosigs /etc/containers/policy.json*
--

7. Enable and Start MicroShift.

.. Be patient, it will take a few moments until MicroShift generates Kubernetes configuration files, pulls all its containers, and starts its services and pods. Be warned that it will NOT be ready when the `systemctl start` command returns.
+
[source,subs="verbatim,quotes"]
--
$ *systemctl enable microshift*
$ *systemctl start microshift*
--

.. Check that the microshift service, which includes the Kubernetes core daemons, has started, and shows no errors on its logs, but be warned that having a healthy MicroShift service does NOT mean it's fully ready and available.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl status microshift*
[GRAB OUTPUT]
--

8. Verify that MicroShift is fully initialized.

.. Copy the autogenerated Kubeconfig file to your home directory and change its ownership so you can read it from your unprivileged user. Do not make that file read-write, let it stay unchanged as a "breaking class" resort.
+
[source,subs="verbatim,quotes"]
--
$ *sudo cp /var/lib/microshift/resources/kubeadmin/kubeconfig ~/local-admin*
$ *sudo chown student:student ~/local-admin*
--

.. Check all pods running on MicroShift. It may take a while until all of them are ready and running.
+
[source,subs="verbatim,quotes"]
--
$ *oc --kubeconfig ~/local-admin get pod -A*
NAMESPACE              	NAME                                   	READY   STATUS	RESTARTS    	AGE
kube-system            	csi-snapshot-controller-69ddff88c8-hr9dt   1/1 	Running   0           	6m37s
kube-system            	csi-snapshot-webhook-74dc497864-hfdw7  	1/1 	Running   0           	6m41s
openshift-dns          	dns-default-9z4ph                      	2/2 	Running   0           	5m55s
openshift-dns          	node-resolver-prvjx                    	1/1 	Running   0           	6m39s
openshift-ingress      	router-default-575b4fc7-tg5lz          	1/1 	Running   0           	6m37s
openshift-ovn-kubernetes   ovnkube-master-wj4gv                   	4/4 	Running   1 (5m57s ago)   6m39s
openshift-ovn-kubernetes   ovnkube-node-fdpm8                     	1/1 	Running   1 (5m58s ago)   6m39s
openshift-service-ca   	service-ca-9db855698-zd7vg             	1/1 	Running   0           	6m36s
openshift-storage      	lvms-operator-7f544467bc-cqf2n         	1/1 	Running   0           	6m40s
openshift-storage      	vg-manager-tjrs2                       	1/1 	Running   0           	5m25s
--

.. As an additional sanity check, verify that your Kubernetes cluster contains one node which takes the roles of both control plane and worker node.
+
[source,subs="verbatim,quotes"]
--
$ *oc --kubeconfig local-admin get node*
NAME 	STATUS   ROLES                     	AGE 	VERSION
rhelvm   Ready	control-plane,master,worker   7m31s   v1.30.5
--

With this last step, you have a fully functional deployment of MicroShift in a RHEL machine. If you find that any of the MicroShift pods failed to start, the most likely cause is an error in your registry mirror and image policy configurations.

IMPORTANT: The way we configured MicroShift, it does NOT contain a pull secret to download container images from Red Hat, even if it has access to the Internet. It can only pull containers from its mirror registry, which is usually what organizations with stricty security policies demand.

== Next Steps

You probably don't want to perform development from the machine running MicroShift, so the next activity will configure MicroShift for remote access and also an unprivileged user, without full Kubernetes administration rights.
