:time_estimate: 5

= Lab: Access MicroShift as a Developer or Platform Engineer

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Configure remote access to MicroShift as privileged and unprivileged users.

WARNING: Work In Progress

== Before you Begin

You need a _test machine_ where you installed, configured, and verified MicroShift, by following the instructions from the xref:s2-install-lab.adoc[previous lab].

You also need a _development machine_ from which you will access the MicroShift instance on your _test machine_.

Finally, you also need a _mirror registry_ machine, already configured with a mirror registry for Red Hat OpenShift and pre-populared with container images required by MicroShift and applications samples. Make sure that your _mirror registry machine_ machine was configured and verified by following the instructions from the xref:ch1-microshift:s3-prepare-lab.adoc[first lab].

These instructions were tested on RHEL 9.4 [tentative!] but should work with minimal or no change on newer and older RHEL 9.x releases.

If you are using the course classroom, you will log in on the `workstation` VM, which is your _development machine_, as the user `student` with password `student`, and you start SSH sessions from `workstation` VM to the `serverb` VM, which is your _test machine_, using the same user. If not, please adapt the instructions to your test environment.

You will perform all steps in this lab on your _test machine_.

== Instructions

1. Log in on your _test machine_ and verify that MicroShift is up and running.

.. Check that the MicroShift service is active.
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl is-active microshift*
active
--

.. Check that all pods are running and all their containers are ready and all their containers are running
+
[source,subs="verbatim,quotes"]
--
$ *oc --kubeconfig ~/local-admin get pod -A*
NAMESPACE              	NAME                                   	READY   STATUS	RESTARTS    	AGE
kube-system            	csi-snapshot-controller-69ddff88c8-hr9dt   1/1 	Running   0           	6m37s
kube-system            	csi-snapshot-webhook-74dc497864-hfdw7  	1/1 	Running   0           	6m41s
openshift-dns          	dns-default-9z4ph                      	2/2 	Running   0           	5m55s
openshift-dns          	node-resolver-prvjx                    	1/1 	Running   0           	6m39s
openshift-ingress      	router-default-575b4fc7-tg5lz          	1/1 	Running   0           	6m37s
openshift-ovn-kubernetes   ovnkube-master-wj4gv                   	4/4 	Running   1 (5m57s ago)   6m39s
openshift-ovn-kubernetes   ovnkube-node-fdpm8                     	1/1 	Running   1 (5m58s ago)   6m39s
openshift-service-ca   	service-ca-9db855698-zd7vg             	1/1 	Running   0           	6m36s
openshift-storage      	lvms-operator-7f544467bc-cqf2n         	1/1 	Running   0           	6m40s
openshift-storage      	vg-manager-tjrs2                       	1/1 	Running   0           	5m25s
--
+
Remember that you copied the autogenerated kubeconfig file to `~/local-admin` in the xref:s2-install-lab.adoc[previous lab]

2. Create a namespace and a service account with limited read-write access to that namespace.
+
[source,subs="verbatim,quotes"]
--
$ *export KUBECONFIG=~/local-admin*
$ *oc create namespace user*
namespace/user created
$ *oc create sa user -n user*
serviceaccount/user created
$ *oc create rolebinding user --clusterrole edit --serviceaccount user:user -n user*
--
+
[source,subs="verbatim,quotes"]
--
$ *oc --as system:serviceaccount:user:user get sa -n user*
NAME      SECRETS   AGE
default   0         8m48s
user      0         6m58s
$ *oc --as system:serviceaccount:user:user get sa -n default*
Error from server (Forbidden): serviceaccounts is forbidden: User "system:serviceaccount:user:user" cannot list resource "serviceaccounts" in API group "" in the namespace "default"
$ *oc --as system:serviceaccount:user:user get node*
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:user:user" cannot list resource "nodes" in API group "" at the cluster scope
--
+
[source,subs="verbatim,quotes"]
--
$ *oc --as system:serviceaccount:user:user create configmap test1 --from-literal one=1 -n user*
NAME      SECRETS   AGE
default   0         8m48s
user      0         6m58s
$ *oc get configmap -n user*
NAME                       DATA   AGE
kube-root-ca.crt           1      15m
openshift-service-ca.crt   1      15m
test1                      1      11s
--

3. Create another namespace and grant limited read-only access to the service account.
+
[source,subs="verbatim,quotes"]
--
$ *oc create namespace project*
namespace/project created
$ *oc create rolebinding user --clusterrole view --serviceaccount user:user -n project*
--
+
[source,subs="verbatim,quotes"]
--
$ *oc create configmap test2 --from-literal two=2 -n project*
configmap/test2 created
$ *oc --as system:serviceaccount:user:user get configmap -n project*
NAME                       DATA   AGE
kube-root-ca.crt           1      89s
openshift-service-ca.crt   1      89s
test2                      1      35s
$ *oc --as system:serviceaccount:user:user create configmap test3 --from-literal three=3 -n project*
error: failed to create configmap: configmaps is forbidden: User "system:serviceaccount:user:user" cannot create resource "configmaps" in API group "" in the namespace "project"
--

4. Create a kubeconfig file with the token for the service account.
+
[source,subs="verbatim,quotes"]
--
$ *cat <<EOF >user-token.yaml*
apiVersion: v1
kind: Secret
metadata:
  name: user-token
  annotations:
    kubernetes.io/service-account.name: "user"
type: kubernetes.io/service-account-token
EOF
$ *oc apply -f user-token.yaml -n user*
secret/user-token created
$ *mkdir temp-token*
$ *--keys token --to . -n user*
token
--
+
[source,subs="verbatim,quotes"]
--
$ unset KUBECONFIG
$ sudo cp /var/lib/microshift/resources/kubeadmin/serverb/kubeconfig ~/remote-admin
$ sudo chown student:student ~/remote-admin
$ chmod a-w ~/remote-admin
$ cp remote-admin remote-user
$ oc --kubeconfig ~/remote-user config delete-user user
deleted user user from /home/student/remote-user
$ oc --kubeconfig ~/remote-user config set-credentials user --token $(cat token)
User "user" set.
$ oc --kubeconfig ~/remote-user config set-context microshift --namespace user --user user --cluster microshift
Context "microshift" modified.
$ oc --kubeconfig ~/remote-user get configmap
NAME                       DATA   AGE
kube-root-ca.crt           1      107m
openshift-service-ca.crt   1      107m
test1                      1      92m
--

5. Grant the unprivileged user rights to impersonate a cluster-admin
+
[ Cannot use system: users, so must reference an unexistant "admin" user ]
+
[source,subs="verbatim,quotes"]
--
$ oc --kubeconfig ~/local-admin whoami
system:admin
$ oc --kubeconfig ~/local-admin create clusterrolebinding cluster-admin-user --clusterrole cluster-admin --user admin
clusterrolebinding.rbac.authorization.k8s.io/cluster-admin-user created
$ oc --kubeconfig ~/local-admin create clusterrole sudo-admin --resource users --resource-name admin --verb impersonate
clusterrole.rbac.authorization.k8s.io/sudo-admin created
$ oc --kubeconfig ~/local-admin create clusterrolebinding sudo-user --clusterrole sudo-admin --serviceaccount user:user
clusterrolebinding.rbac.authorization.k8s.io/sudo-user created
$ oc --kubeconfig ~/remote-user whoami
system:serviceaccount:user:user
$ oc --kubeconfig ~/remote-user get nodes
Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:user:user" cannot list resource "nodes" in API group "" at the cluster scope
$ oc --kubeconfig ~/remote-user --as admin get nodes
NAME      STATUS   ROLES                         AGE   VERSION
serverb   Ready    control-plane,master,worker   25h   v1.30.5
--

6. Allow remote access to MicroShift on the system firewall and Test a kubeconfig file for remote access as cluster administrator.
+
[source,subs="verbatim,quotes"]
--
$ sudo cp /var/lib/microshift/resources/kubeadmin/serverb/kubeconfig ~/remote-admin
$ sudo chown student:student ~/remote-admin
$ chmod a-w ~/remote-admin
$ oc --kubeconfig ~/remote-admin get node
NAME      STATUS   ROLES                         AGE   VERSION
serverb   Ready    control-plane,master,worker   23h   v1.30.5
$ sudo firewall-cmd --permanent --zone=public --add-port=6443/tcp
success
$ sudo firewall-cmd --reload
success
--

7. Switch to your _development machine_ and copy the kubeconfig files for cluster administrator and service account.
+
[source,subs="verbatim,quotes"]
--
$ scp serverb:~/remote-admin .
$ chmod a-w ~/remote-admin
[student@workstation ~]$ oc --kubeconfig ~/remote-admin get node
NAME      STATUS   ROLES                         AGE   VERSION
serverb   Ready    control-plane,master,worker   24h   v1.30.5
[student@workstation ~]$ oc --kubeconfig ~/remote-user get configmap
NAME                       DATA   AGE
kube-root-ca.crt           1      115m
openshift-service-ca.crt   1      115m
test                       1      100m
[student@workstation ~]$ oc --kubeconfig ~/remote-user get configmap -n project
NAME                       DATA   AGE
kube-root-ca.crt           1      99m
openshift-service-ca.crt   1      99m
test2                      1      98m
$ oc --kubeconfig ~/remote-user --as admin get node
NAME      STATUS   ROLES                         AGE   VERSION
serverb   Ready    control-plane,master,worker   25h   v1.30.5
--

You now have [ SOMETHING ] or did [ SOMETHING ]

== Next Steps

Lorem ipsum
